### ISSUE TITLE
Using a password?

### ISSUE THREAD

**Issue by vendethiel** [JakobOvrum/Diggler#3]
Hi,

it seems it's not possible in the crurent code of diggler/dirk to join a network with an account that has a password. Am I missing something? A github code search only brings up dirk's "join channel with a password".

Thanks!

**Comment by vendethiel** [comment]
https://github.com/JakobOvrum/Dirk/blob/44a17ce5efd8fccc6aea055e6f3bea89ff4abcbf/irc/client.d#L137 I guess

**Comment by JakobOvrum** [comment]
That's right. I haven't had time to get around to this. I'll be back working on Dirk in perhaps ~3 weeks, hopefully sooner.

**Comment by vendethiel** [comment]
I was just wondering if anything special was necessary. I don't know anything about the protocol itself, but if it's just a matter of adding a field, documenting it, and adding a "PASS: {pass}" message, then yes I can probably do it :)
