### ISSUE TITLE
onNickInUse not working as intended

### ISSUE THREAD

**Issue by mitchgrout** [JakobOvrum/Diggler#6]
Using the example code found here http://jakobovrum.github.io/Diggler/index.html , if I connect to an IRC serer (tested on Rizon & Esper) where the nick is already in use, the client sends "NICK *_" instead of the original nick with an appended underscore.
Log from running with "debugVersions": ["Dirk"]
>> ":irc.losslessone.com 433 * mitch_ :Nickname is already in use." pos: 318
<< "NICK *_" (length: 7)
>> ":irc.losslessone.com 432 * *_ :Erroneous Nickname" pos: 369
Unhandled command "432"

**Comment by JakobOvrum** [comment]
Fixed by https://github.com/JakobOvrum/Dirk/commit/8237150c19189999a373f853fc2c6053c720e86a
