### ISSUE TITLE
Suggestion for help command

### ISSUE THREAD

**Issue by mitchgrout** [JakobOvrum/Diggler#8]
For the default help command, I suggest that it echoes only the added command sets, instead of echoing every command set and their commands on a separate line. This will avoid flooding a channel if a large number of command sets have been added to the bot. The help command should also be modified so you can ask for help for a specific command set, and get the commands it defines.

**Comment by JakobOvrum** [comment]
The help command is implemented using the same interface as user commands: https://github.com/JakobOvrum/Diggler/blob/master/src/diggler/defaultcommands.d#L22

Maybe you want to try implementing this yourself? :)
